spring:
 application:
  name: auctionSystem
 datasource:
  url: jdbc:mysql://localhost:3306/auction_system
  username: root
  password: qwe123qwe
  driver-class-name: com.mysql.cj.jdbc.Driver 
 flyway:
  baseline-on-migrate: true

server:
 port: 8080