spring:
  application:
    name: auctionSystem
  datasource:
    url: jdbc:mysql://localhost:3306/auction_system
    username: root
    password: qwe123qwe
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  flyway:
    baseline-on-migrate: true
  web:
    resources:
      static-locations:
        - classpath:/static/
        - classpath:/public/
        - classpath:/resources/
        - classpath:/META-INF/resources/
        - file:E:/Programming_Files/Java Spring Boot/auctionSystemWeb/auctionSystem/userUploads

server:
  port: 8080
